const genres = {
  advertising: [
    'https://www.youtube.com/embed/WaEeMQYmoTY?si=-V95ZPj3p2xTFFMU',
    'https://www.youtube.com/embed/EdTeNIZgS-Q?si=2EcC6yFtXKlZnO2J',
    'https://www.youtube.com/embed/Pn5027x6RmU?si=ALaU8AqKGltNla0F',
    'https://www.youtube.com/embed/H7KdCzEXn_g?si=NZ-ieGYDWEqOsaTw',
    'https://www.youtube.com/embed/_ChBbrgUYDc?si=JwBNYfsEchC8K1jU',
    'https://www.youtube.com/embed/lEwvgTygu5w?si=eW8nse7gmVnOEL5l',
    'https://www.youtube.com/embed/0rRNn8EsFUE?si=MyCmBIs_g_UeQwWw',
    'https://www.youtube.com/embed/8419Ez1_PEM?si=slT2RNs7TWR0QgpF',
    'https://www.youtube.com/embed/JbFek2Va_A0?si=52z-5EwMCJ5GguSn',
    'https://www.youtube.com/embed/OeD89VxYaM0?si=PYiFJCQBH0UjKV1N',
  ],
  promo: [
    'https://www.youtube.com/embed/rL6QgLXa0V0?si=GG8bF0Xr5oU2T8Y2',
    'https://www.youtube.com/embed/DPb_V8nd4J0?si=kIK3CFNK8myVrEUU',
    'https://www.youtube.com/embed/m1rEtUBokcM?si=lpT4wE-47DjcwgGD',
    'https://www.youtube.com/embed/SlN97FBwiNY?si=nVbYJ_cj_xnK8pXt',
    'https://www.youtube.com/embed/34ojt0kfp_g?si=UTu-cV_vPtpcCaBQ',
    'https://www.youtube.com/embed/AZGT3h_cSVo?si=u0MjpR09ArvFDIB7',
    'https://www.youtube.com/embed/qtKEJskSnk0?si=G9x26vDDeaVCGqXV',
    'https://www.youtube.com/embed/c8aaLQiSgFA?si=4ikQWVXOpyfKqx0E',
  ],
  documentary: [
    'https://www.youtube.com/embed/uvW31Ed3Gzg?si=U13Dr3TTqckAJ45c',
    'https://www.youtube.com/embed/36Ac1Q_zngE?si=DDF-TE_cIJXGoxgW',
    'https://www.youtube.com/embed/ZkOMVQ0eECY?si=24QkabBosRsXjFiT',
    'https://www.youtube.com/embed/xMR70mngSCA?si=fztZSncl7ueJEYIq',
    'https://www.youtube.com/embed/r1_RQG8UQgE?si=HYfIskKkbaXsGe3G',
    'https://www.youtube.com/embed/mZ1CXargk_g?si=KHYSGzA5oBCV-jRT',
    'https://www.youtube.com/embed/HI9jtCxARxc?si=3oDFQpD2uqHkMDCp',
    'https://www.youtube.com/embed/R-p_JsZyFoE?si=AUfjlNttquHTUmag',
  ],
  business: [
    'https://www.youtube.com/embed/orrfOQz5Ypw?si=m9-gWxKyGMRtOLFY',
    'https://www.youtube.com/embed/zCXEWtEyFig?si=NMI9Ssn-JSxIyDcg',
    'https://www.youtube.com/embed/S9285RNmlwA?si=FYQFNUbXdw1Rw_vJ',
    'https://www.youtube.com/embed/w9f7-CfYoJs?si=gppMCIuniaPViGOB',
    'https://www.youtube.com/embed/RJ15MvQ8fOs?si=d3HAIuzIC578hNJw',
    'https://www.youtube.com/embed/vrfVugbn124?si=bsdlV7TaKZT-EEdH',
    'https://www.youtube.com/embed/oR8b9WEeHOA?si=s-H8ps7H-6u9m7Q0',
    'https://www.youtube.com/embed/rG53W0_0TeY?si=uB7DxahVJLcf9WRK',
    'https://www.youtube.com/embed/79JKUSMStAE?si=sPDlzeejUnelyONM',
    'https://www.youtube.com/embed/OU_Wct4IzNQ?si=sHatRxhv47-kQ2yQ',
    'https://www.youtube.com/embed/SlxAyeFRGn4?si=QoBd9Ff1lq7IDNsl',
    'https://www.youtube.com/embed/pnTZvnVW6Gg?si=ROjFd_ky7ULeRbOe',
  ],
  wedding: [
    'https://www.youtube.com/embed/v1ZVN9QF23I?si=s-QND3U7B6cdCquE',
    'https://www.youtube.com/embed/5U_Gzsa9Z7w?si=FUckD393nAbiVPWo',
    'https://www.youtube.com/embed/Brbp18YmjW8?si=lxEKCe8L4ITzLw-H',
    'https://www.youtube.com/embed/uq9dUa1c3Zg?si=wDwEOB_yw-DZQ3XY',
    'https://www.youtube.com/embed/Tnt3rIHLu-k?si=P-NXy-xwLhszCI9E',
    'https://www.youtube.com/embed/Dzab0weu06Q?si=AmWns_kPi0-g1edk',
    'https://www.youtube.com/embed/Yak8vzSoLOo?si=tU9zTrYE-Yom0Rh-',
    'https://www.youtube.com/embed/8jCCI7Ei0jc?si=aEc0w8Be5eLRgPmA',
  ],
  graphics: [
    'https://www.youtube.com/embed/Z0aUsUKbx5M?si=Ot2nY8UjZIme2tCT',
    'https://www.youtube.com/embed/hIiK7YBpplg?si=gCnZmO3D_eOmd5g1',
    'https://www.youtube.com/embed/HXMe5w2P1g8?si=YYLOMF84QyesLyyA',
    'https://www.youtube.com/embed/Tu65UqOyVoQ?si=JreKoU_zD-3lE1yl',
    'https://www.youtube.com/embed/Fgxi2D8rEqI?si=rOZxqimZuJBYPMdX',
  ],
  activities: [
    'https://www.youtube.com/embed/NlPzgcOf2yY?si=VEdlWqy5VOms-yZq',
    'https://www.youtube.com/embed/GGNNe6e7SqI?si=chNRcNW0FkWjAMZA',
    'https://www.youtube.com/embed/AMHvnD3Vf_s?si=hIQD24lj-DKJ2DQH',
    'https://www.youtube.com/embed/F53X6drJ3QQ?si=f7ctsu-CV7yIcI6M',
    'https://www.youtube.com/embed/wSG_gK_IEIs?si=ax0K1vL4B0Od7ita',
    'https://www.youtube.com/embed/Mn7zLX9SasY?si=DzG_DPdKJ2fSNY0z',
    'https://www.youtube.com/embed/W4KlQkSzxGE?si=l-09Ukh33ATt1xrH',
    'https://www.youtube.com/embed/AOAdYmEDQx0?si=zDyoX6YdQysYt56n',
    'https://www.youtube.com/embed/VpB6yRuP1m4?si=4XYyxetl5v--_Z7B',
    'https://www.youtube.com/embed/_jHMSY6Ot8E?si=goHfp_36KDtEtIN_',
  ],
  broadcasts: [
    'https://www.youtube.com/embed/Om-VteTyh_4?si=oDV-rPRGTtePynWS',
    'https://www.youtube.com/embed/knFISBuZ9IA?si=0kBLvo29vzsffUtJ',
  ],
};

export default genres;
